development:
  adapter: postgresql
  encoding: utf8
  database: wine_db 
  pool: 5
  username: dev 
  password: asdfasdf

test:
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: dev 
  password: asdfasdf
